//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.22 at 09:56:00 AM EEST 
//


package wse.bdovbysh.entity;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the wse.bdovbysh.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Item_QNAME = new QName("http://wse-bdovbysh.rhcloud.com/ws", "item");
    private final static QName _Result_QNAME = new QName("http://wse-bdovbysh.rhcloud.com/ws", "result");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: wse.bdovbysh.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetItemSumRequest }
     * 
     */
    public GetItemSumRequest createGetItemSumRequest() {
        return new GetItemSumRequest();
    }

    /**
     * Create an instance of {@link Items }
     * 
     */
    public Items createItems() {
        return new Items();
    }

    /**
     * Create an instance of {@link GetItemSumResponse }
     * 
     */
    public GetItemSumResponse createGetItemSumResponse() {
        return new GetItemSumResponse();
    }

    /**
     * Create an instance of {@link GetCalcRequest }
     * 
     */
    public GetCalcRequest createGetCalcRequest() {
        return new GetCalcRequest();
    }

    /**
     * Create an instance of {@link CalcRequestType }
     * 
     */
    public CalcRequestType createCalcRequestType() {
        return new CalcRequestType();
    }

    /**
     * Create an instance of {@link GetCalcResponse }
     * 
     */
    public GetCalcResponse createGetCalcResponse() {
        return new GetCalcResponse();
    }

    /**
     * Create an instance of {@link GetCountryResponse }
     * 
     */
    public GetCountryResponse createGetCountryResponse() {
        return new GetCountryResponse();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link GetCountryRequest }
     * 
     */
    public GetCountryRequest createGetCountryRequest() {
        return new GetCountryRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wse-bdovbysh.rhcloud.com/ws", name = "item")
    public JAXBElement<BigDecimal> createItem(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Item_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://wse-bdovbysh.rhcloud.com/ws", name = "result")
    public JAXBElement<BigDecimal> createResult(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Result_QNAME, BigDecimal.class, null, value);
    }

}
