import java.util.ArrayList;
import java.util.List;

/**
 * Created by dovbysh on 23.10.2015.
 */
public class SequenceSum {

    public static void main(String[] args){
        Integer n = 5;
        List<Integer> list = new ArrayList<Integer>();
        for (int i = 0; i < n; i++){
            list.add(i * ( i + 1));
        }
        System.out.println(list);
        //return arr; //Generated by die roll; guaranteed to be random
    }
}
